interface:
  background_img: background_jpg/b2.jpg
  lab_img: background_jpg/lab.png
  lab_screen_size: [600,350]
  refresh_sound_file: Sound_effect/refresh.wav
  upgrade_sound_file: Sound_effect/pay.wav
  save_sound_file: Sound_effect/ensure.wav
  error_sound_file: Sound_effect/error.wav
  exit_sound_file: Sound_effect/tip.wav
  screen_size: [165,220]
  lab_grid:
    background_color: "#2C3B35"
    button_color: "#448856"
    gold_icon: [15,45]
    gold_value: [40,47]
    diamond_icon: [110,45]
    diamond_value: [135,47]
    refresh_icon: [265,20]
    save_icon: [265,45]
    consume_grid: [[64,91],[64,139],[64,185],[64,231],[64,275],[64,323],[364,91],[364,139],[364,185],[364,231],[364,275],[364,323]]
    level_grid: [[192,75],[192,122],[192,169],[192,215],[192,261],[192,308],[495,75],[495,122],[495,169],[495,215],[495,261],[495,308]]
setting:
  sim_interval: 10  # (ms)
  screen_size: [480,600]
  status_bar_size: [480,30]
  gamescreen_size: [480,570]
  background_color: [0,0,0]
  bg_rollv: 18
  scene_path: data/scene.json
  success_sound_file: Sound_effect/mission_accomplished.wav
  fail_sound_file: Sound_effect/mission_failed.wav
  fail_font_pos: [100,300]
  success_font_pos: [70,300]

player:
  missile:
    img: missile_png/missile0.png
    explode_sound_file: bomb_fire.wav
  mp3_path: Sound_effect/
  bullet_sound_file: fighter_bullet_fire.mp3
  missile_sound_file: fighter_missile_fire.mp3
  explode_sound_file: fighter_explode.mp3
  hit_sound_file: hurt2.wav


bullet:
  path: bullet_png/
  setting: data/bullet_info.csv

enemy:
  path: enemy_png/
  setting: data/enemy_info.csv
  explode_sound_file: Sound_effect/small_explode.wav
  big_explode_sound_file: Sound_effect/fighter_explode.mp3
  hurt_sound_file: Sound_effect/metal1.mp3
  diamond_sound_file: Sound_effect/diamond.wav


enemyfire:
  path: enemyfire_png/
  setting: data/enemyfire_info.csv
  type_a_sound_file: Sound_effect/laser_big_oneshot.mp3
  type_b_sound_file: Sound_effect/launch1.wav
  explode_sound_file: Sound_effect/bomb_fire.wav
enemy_path:
  path: path_josn

icon:
  path: icon_png/
  diamond: diamond.png
  gold: gold.png
  heart: heart.png
  lightning: lightning.png
  snow: snowflake.png
  warn: [warn1.png, warn2.png]
  cool: water_drop.png
  upgrade: upgrade.png
  refresh: refresh.png
  save: save.png
