interface:
  background_img: background_jpg/b2.jpg
  lab_img: background_jpg/lab.png
  lab_screen_size: [560,360]
  refresh_sound_file: Sound_effect/refresh.wav
  upgrade_sound_file: Sound_effect/upgrade.wav
  error_sound_file: Sound_effect/error.wav
  screen_size: [165,220]
  lab_grid:
    gold_icon: [20,45]
    gold_value: [50,47]
    diamond_icon: [130,45]
    diamond_value: [160,47]
    refresh_ico: [255,26]

setting:
  sim_interval: 10  # (ms)
  screen_size: [480,600]
  status_bar_size: [480,30]
  gamescreen_size: [480,570]
  background_color: [0,0,0]
  bg_rollv: 18
  scene_path: data/scene.json

player:
  missile:
    img: missile_png/missile0.png
    explode_sound_file: bomb_fire.wav
  mp3_path: Sound_effect/
  bullet_sound_file: fighter_bullet_fire.mp3
  missile_sound_file: fighter_missile_fire.mp3
  explode_sound_file: fighter_explode.mp3
  hit_sound_file: hurt2.wav


bullet:
  path: bullet_png/
  setting: data/bullet_info.csv

enemy:
  path: enemy_png/
  setting: data/enemy_info.csv
  explode_sound_file: Sound_effect/small_explode.wav
  big_explode_sound_file: Sound_effect/fighter_explode.mp3
  hurt_sound_file: Sound_effect/metal1.mp3
  diamond_sound_file: Sound_effect/diamond.wav


enemyfire:
  path: enemyfire_png/
  setting: data/enemyfire_info.csv
  type_a_sound_file: Sound_effect/laser_big_oneshot.mp3
  type_b_sound_file: Sound_effect/launch1.wav
  explode_sound_file: Sound_effect/bomb_fire.wav
enemy_path:
  path: path_josn

icon:
  path: icon_png/
  diamond: diamond.png
  gold: gold.png
  heart: heart.png
  lightning: lightning.png
  snow: snowflake.png
  warn: [warn1.png, warn2.png]
  cool: water_drop.png
  upgrade: upgrade.png
  refresh: refresh.png
